# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP5rAfrXZypmcIdoG6Q7Xh6KX7rHuGIh
"""



import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from transformers import pipeline

df = pd.read_csv("financial_news.csv", encoding="latin-1", header=None)
df.columns = ["sentiment", "text"]
df["sentiment"] = df["sentiment"].str.lower().str.strip()
df.head()

X_train, X_test, y_train, y_test = train_test_split(
    df["text"], df["sentiment"], test_size=0.2, random_state=42, stratify=df["sentiment"]
)

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2), stop_words="english")
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_tfidf, y_train)
rf_y_pred = rf_model.predict(X_test_tfidf)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_y_pred))
print("Random Forest Classification Report:\n", classification_report(y_test, rf_y_pred))

cm = confusion_matrix(y_test, y_pred, labels=["positive","neutral","negative"])
plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Positive","Neutral","Negative"],
            yticklabels=["Positive","Neutral","Negative"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

sentiment_llm = pipeline("sentiment-analysis", model="ProsusAI/finbert")

sample_texts = X_test.sample(10, random_state=42)
results = []
for t in sample_texts:
    results.append(sentiment_llm(t)[0]["label"].lower())
pd.DataFrame({
    "text": sample_texts.values,
    "actual": y_test.loc[sample_texts.index].values,
    "llm_predicted": results
})

# Read input from user
user_text = input("Enter a financial news headline or sentence:\n")

# -------- Classical ML Prediction --------
user_tfidf = tfidf.transform([user_text])
ml_prediction = model.predict(user_tfidf)[0]

# -------- LLM Zero-Shot Prediction --------
llm_result = sentiment_llm(user_text)[0]
llm_prediction = llm_result["label"].lower()
llm_confidence = llm_result["score"]

# -------- Display Results --------
print("\n--- Sentiment Prediction Results ---")
print(f"Input Text: {user_text}\n")

print("Classical ML Model Prediction:")
print(f" → Sentiment: {ml_prediction}")

print("\nLLM Zero-Shot (FinBERT) Prediction:")
print(f" → Sentiment: {llm_prediction}")
print(f" → Confidence Score: {llm_confidence:.2f}")
